export const TEST_DISPATCH = "TEST_DISPATCH";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";

export const GET_PRODUCTS_BY_SELL = 'GET_PRODUCTS_BY_SELL';
export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCTS_BY_ARRIVAL';